name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: install eslint
      run: yarn add eslint
    - name: Run ESLint
      run: yarn run --init eslint ./ --ext .js,.jsx,.ts,.tsx
